### ISSUE TITLE
Issue in filtering step

### ISSUE THREAD

**Issue by ValentinaBoP** [WGLab/LinkedSV#15]
Hello,

I'm using LinkedSV on some 10X data to call somatic insertions and the software throws an error during the filtering step:

```
[...]
[09/17/2020 18:21:44 (181.289 MB)] merging SV candidates
[09/17/2020 18:21:44 (181.289 MB)] merging candidate calls
[09/17/2020 18:21:44 (181.289 MB)] building edges for candidate calls
[09/17/2020 18:21:44 (181.289 MB)] connected components
[09/17/2020 18:21:44 (181.391 MB)] filtering SV calls
[09/17/2020 18:21:44 (181.391 MB)] reading black region bed file: lycPyr7.4.fasta.black.bed
[09/17/2020 18:21:44 (184.639 MB)] reading gap region bed file: lycPyr7.4.fasta.gaps.bed
[09/17/2020 18:21:44 (184.639 MB)] number of retained SVs: 6
[09/17/2020 18:21:44 (184.639 MB)] reading low mapq bcd21 file: /crex/proj/sllstore2017073/private/Valentina/2020ChrW/Intermediate/LinkedSV/astRot/phased_possorted_bam.bam.low_mapq.bcd21.gz
[09/17/2020 18:22:29 (186.909 MB)] processed 10000000 reads
[09/17/2020 18:23:14 (188.985 MB)] processed 20000000 reads
[09/17/2020 18:23:19 (189.325 MB)] finished reading low mapq bcd21 file: /crex/proj/sllstore2017073/private/Valentina/2020ChrW/Intermediate/LinkedSV/astRot/phased_possorted_bam.bam.low_mapq.bcd21.gz
Traceback (most recent call last):
  File "/home/vpeona/LinkedSV/linkedsv.py", line 313, in <module>
    main()
  File "/home/vpeona/LinkedSV/linkedsv.py", line 59, in main
    filter_calls.filter_calls(args, dbo_args, endpoint_args)
  File "/domus/h1/vpeona/LinkedSV/scripts/filter_calls.py", line 106, in filter_calls
    round3_retained_sv_list = filter_calls_2d (round2_retained_sv_list, args.black_region_2d_file, args.filter_bedpe_file, remove_chr_prefix)
  File "/domus/h1/vpeona/LinkedSV/scripts/filter_calls.py", line 295, in filter_calls_2d
    black_list_2array_dict, bin_size = read_2d_blacklist_file(black_list_file, remove_chr_prefix)
  File "/domus/h1/vpeona/LinkedSV/scripts/filter_calls.py", line 373, in read_2d_blacklist_file
    black_list_fp = gzip.open(black_list_file, 'rt')
  File "/proj/uppstore2018073/private/Valentina/Conda/LinkedSV/lib/python3.5/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/proj/uppstore2018073/private/Valentina/Conda/LinkedSV/lib/python3.5/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: ''
```

The files in my output directory:

```
-rw-rw-r-- 1 vpeona sllstore2017073      11097 Sep 17 17:43 phased_possorted_bam.bam.arguments
-rw-rw-r-- 1 vpeona sllstore2017073  243227179 Sep 17 17:42 phased_possorted_bam.bam.barcode_cov.bed
-rw-rw-r-- 1 vpeona sllstore2017073        628 Sep 17 17:20 phased_possorted_bam.bam.barcode_statistics
-rw-rw-r-- 1 vpeona sllstore2017073  343654012 Sep 17 18:02 phased_possorted_bam.bam.bcd11
-rw-rw-r-- 1 vpeona sllstore2017073  858454179 Sep 17 18:03 phased_possorted_bam.bam.bcd12
-rw-rw-r-- 1 vpeona sllstore2017073  535375767 Sep 17 18:21 phased_possorted_bam.bam.bcd13
-rw-rw-r-- 1 vpeona sllstore2017073 5571152198 Sep 17 17:20 phased_possorted_bam.bam.bcd21.gz
-rw-rw-r-- 1 vpeona sllstore2017073  689661793 Sep 17 17:41 phased_possorted_bam.bam.bcd22
-rw-rw-r-- 1 vpeona sllstore2017073  548627098 Sep 17 17:35 phased_possorted_bam.bam.bcd22.tmp
-rw-rw-r-- 1 vpeona sllstore2017073      17664 Sep 17 17:49 phased_possorted_bam.bam.bk_cand_pairs
-rw-rw-r-- 1 vpeona sllstore2017073        735 Sep 17 17:43 phased_possorted_bam.bam.fragment_statistics
-rw-rw-r-- 1 vpeona sllstore2017073      17618 Sep 17 17:42 phased_possorted_bam.bam.high_cov.bed
-rw-rw-r-- 1 vpeona sllstore2017073  529268507 Sep 17 17:30 phased_possorted_bam.bam.low_mapq.bcd21.gz
-rw-rw-r-- 1 vpeona sllstore2017073    8723345 Sep 17 17:43 phased_possorted_bam.bam.node33
-rw-rw-r-- 1 vpeona sllstore2017073       4118 Sep 17 17:49 phased_possorted_bam.bam.node_cluster33
-rw-rw-r-- 1 vpeona sllstore2017073       4034 Sep 17 17:49 phased_possorted_bam.bam.node_cluster35
-rw-rw-r-- 1 vpeona sllstore2017073       3182 Sep 17 17:49 phased_possorted_bam.bam.node_cluster53
-rw-rw-r-- 1 vpeona sllstore2017073       4012 Sep 17 17:49 phased_possorted_bam.bam.node_cluster55
-rw-rw-r-- 1 vpeona sllstore2017073      17532 Sep 17 18:21 phased_possorted_bam.bam.qbkpair.bedpe
-rw-rw-r-- 1 vpeona sllstore2017073       4119 Sep 17 18:21 phased_possorted_bam.bam.raw_large_svcalls.bedpe
-rw-rw-r-- 1 vpeona sllstore2017073  347212918 Sep 17 17:53 phased_possorted_bam.bam.read_depth.txt
-rw-rw-r-- 1 vpeona sllstore2017073  145246020 Sep 17 17:41 phased_possorted_bam.bam.weird_reads.txt
```

I'm using Python 3.5.5.

Could you help me solving the problem?

Thank you,
Valentina

**Comment by fangli80** [comment]
Hi Valentina, 
could you please show me your commands?

**Comment by ValentinaBoP** [comment]
the command I used is this:

```
conda activate /proj/uppstore2018073/private/Valentina/Conda/LinkedSV

cd <out dir>/Intermediate/LinkedSV

ml bioinfo-tools samtools BEDTools

REF=genome.fasta
GAP=genome.fasta.gaps.bed
BLACK=genome.fasta.black.bed

for BOP in astRot cinMag cinReg
do

if [ ! -d "$DIRECTORY" ]; then
 # make output directory
 mkdir $BOP
fi

# specify input file
INPUT=<input dir>/$BOP/outs/phased_possorted_bam.bam

# run LinkedSV in somatic mode
python /home/vpeona/LinkedSV/linkedsv.py -i $INPUT -d ./$BOP -r $REF -t 4 --somatic_mode --gap_region_bed $GAP --black_region_bed $BLACK
done
```

GAP and BLACK are bed files with three columns: scaffold, start and end

**Comment by fangli80** [comment]
Please clone the latest version. This bug is due to the lacking of a 2D blacklist (overlapping barcodes over two genomic positions). I prepared the 2D blacklist for human genome, using the 10X genomics data of multiple individuals. I guess you probably run LinkedSV on your own assembly. In this case, you don't have a 2D blacklist. So I suggest you use more stringent filtering. (e.g. using germline mode). 

Best, 
Li

**Comment by ValentinaBoP** [comment]
I will try what you suggest these days, thank you for the help!

Best,
Valentina
