### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by mzwaig** [WGLab/LinkedSV#21]
Hello,

I've ran your tool on many samples without issue but I'm now getting this error message for one sample and I'm not sure why.

Any ideas would be appreciated.

Thanks,
Melissa

```
Traceback (most recent call last):
  File "/lb/project/tools/LinkedSV/linkedsv.py", line 313, in <module>
    main()
  File "/lb/project/tools/LinkedSV/linkedsv.py", line 50, in main
    detect_decreased_barcode_overlap(args, dbo_args, endpoint_args)
  File "/lb/project/tools/LinkedSV/linkedsv.py", line 164, in detect_decreased_barcode_overlap
    cal_expected_overlap_value.cal_expected_overlap_bcd_cnt(dbo_args.bcd12_file, dbo_args.bcd13_file, is_wgs)
  File "/lb/project/tools/LinkedSV/scripts/cal_expected_overlap_value.py", line 124, in cal_expected_overlap_bcd_cnt
    predict_overlap_bcd_cnt(bcd12_file, out_file, a, b, alpha, logn, min_m1_value, min_m2_value, max_m1_value, max_m2_value, Y_percentile_array, bk_list, c, Y_mean, Y_std_r, Y_std_l, n_window_pairs)
  File "/lb/project/tools/LinkedSV/scripts/cal_expected_overlap_value.py", line 172, in predict_overlap_bcd_cnt
    Y = math.log(predicted_n_ovl_bcd / float(m0), 2)
ValueError: math domain error
```

**Comment by fangli80** [comment]
Hi Melissa, 
Sorry for the late reply. This issue has been solved in a recent commit. Please clone the latest version. 
Best, 
Li
