### ISSUE TITLE
IndexError: cannot do a non-empty take from an empty axes

### ISSUE THREAD

**Issue by levinyi** [WGLab/LinkedSV#23]
hi, everyone, I'm trying to using linkedSV to test my data, my command is below: it shows errors below, anyone can help? 

```
/tools/LinkedSV/linkedsv.py  -i /home/data/shares/JCX_hg38m.bam -r /references/hg38+chrM/hg38.fa -d ./ -v hg38 --germline_mode`
```
this is log file:
```
[06/30/2021 17:18:52 (126.951 MB)] sorting bam file by barcode
[06/30/2021 17:18:52 (126.951 MB)] running command: /tools/LinkedSV/scripts/../bin/output_bam_coreinfo /home/data/shares/JCX_hg38m.bam | samtools sort -l 1 -m 1G -@ 1 -t BX -o /home/user4/work/linkedSV_test/JCX_hg38m.bam.sortbx.bam -
[bam_sort_core] merging from 53 files and 1 in-memory blocks...
[06/30/2021 21:58:49 (126.693 MB)] extracting barcode info from bam file
[06/30/2021 21:58:49 (126.693 MB)] running command: /tools/LinkedSV/scripts/../bin/extract_barcode_info /home/user4/work/linkedSV_test/JCX_hg38m.bam.sortbx.bam __STDOUT__ /home/user4/work/linkedSV_test/JCX_hg38m.bam.barcode_statistics | /tools/LinkedSV/scripts/../bin/pigz --fast --processes 1 - > /home/user4/work/linkedSV_test/JCX_hg38m.bam.bcd21.gz
[06/30/2021 22:12:18 (126.693 MB)] extracting low mapq bcd21
[06/30/2021 22:12:30 (126.693 MB)] clustering reads
[06/30/2021 22:12:30 (126.693 MB)] /tools/LinkedSV/scripts/../bin/cluster_reads /home/user4/work/linkedSV_test/JCX_hg38m.bam.bcd21.gz /home/user4/work/linkedSV_test/JCX_hg38m.bam.bcd22 /home/user4/work/linkedSV_test/JCX_hg38m.bam.weird_reads.txt 1 -1 20 1
started round 1 clustering
finished round 1 clustering
time used is 0.02 seconds
mean and sd of inner size: -1.79769e+308, 0
quantiles of inner size:
1% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
95% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000

quantiles of gap distance:
0.1% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
1% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
25% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
99% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000

inner size cut-off = -2147483648
gap distance cut-off = -2147483648
started round 2 clustering
finished round 2 clustering
time used is 0.01 seconds
total number of reads is: 0
total number of weird reads is: 0
[06/30/2021 22:12:35 (126.845 MB)] searching for extremely high coverage region
[06/30/2021 22:12:42 (126.845 MB)] calculating distribution parameters
[06/30/2021 22:12:42 (126.845 MB)] total number of reads in the genome is: -927534
[06/30/2021 22:12:42 (126.845 MB)] calculating fragment parameters from file: /home/user4/work/linkedSV_test/JCX_hg38m.bam.bcd22
[06/30/2021 22:12:42 (126.845 MB)] N95_fragment_length is: -1
Traceback (most recent call last):
  File "/tools/LinkedSV/linkedsv.py", line 313, in <module>
    main()
  File "/tools/LinkedSV/linkedsv.py", line 47, in main
    detect_increased_fragment_ends(args, dbo_args, endpoint_args)
  File "/tools/LinkedSV/linkedsv.py", line 208, in detect_increased_fragment_ends
    global_distribution.estimate_global_distribution(args, dbo_args, endpoint_args, endpoint_args.bcd22_file)
  File "/tools/LinkedSV/scripts/global_distribution.py", line 133, in estimate_global_distribution
    get_fragment_parameters(args, dbo_args, endpoint_args, global_dist_fp, target_bcd22_file, is_fast_mode)
  File "/tools/LinkedSV/scripts/global_distribution.py", line 213, in get_fragment_parameters
    args.fragment_length_lmda = fit_geometric_distribution(frm_length_list, readpair = False)
  File "/tools/LinkedSV/scripts/global_distribution.py", line 171, in fit_geometric_distribution
    k = np.percentile(length_list, cdf2)
  File "/tools/Python-2.7.16/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3707, in percentile
    a, q, axis, out, overwrite_input, interpolation, keepdims)
  File "/tools/Python-2.7.16/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3826, in _quantile_unchecked
    interpolation=interpolation)
  File "/tools/Python-2.7.16/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3405, in _ureduce
    r = func(a, **kwargs)
  File "/tools/Python-2.7.16/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3941, in _quantile_ureduce_func
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "/tools/Python-2.7.16/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 189, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/tools/Python-2.7.16/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.
```
anyone can help? thanks a lot.

**Comment by fangli80** [comment]
Hi,
could you please use `ls -l` to check the file sizes of all intermediate files generated by LinkedSV? And by the way, is this the full log file? 

Thanks, 
Li

**Comment by levinyi** [comment]
1. this is the all intermediate files:
<img width="941" alt="image" src="https://user-images.githubusercontent.com/12387951/124063210-e1835f00-da64-11eb-8529-09f0d5eb50e4.png">

2, "And by the way, is this the full log file?",  
the full log file are too long in the "quantiles of inner size:" section. so I just deleted the intermediate content.

**Comment by fangli80** [comment]
The intermediate files are too small (a few hundred bytes), which means the sorting step failed (might due to memory issue or I/O issue). Could you please check the full log file and see if you can find anything? Alternatively, you can upload the full log file (zip it if too large) 
best, 
Li

**Comment by levinyi** [comment]
this is the full log file:
```
$ cat  nohup.out
[06/30/2021 17:18:52 (126.951 MB)] sorting bam file by barcode
[06/30/2021 17:18:52 (126.951 MB)] running command: /tools/LinkedSV/scripts/../bin/output_bam_coreinfo /home/data/shares/JCX_hg38m.bam | samtools sort -l 1 -m 1G -@ 1 -t BX -o /home/user4/work/linkedSV_test/JCX_hg38m.bam.sortbx.bam -
[bam_sort_core] merging from 53 files and 1 in-memory blocks...
[06/30/2021 21:58:49 (126.693 MB)] extracting barcode info from bam file
[06/30/2021 21:58:49 (126.693 MB)] running command: /tools/LinkedSV/scripts/../bin/extract_barcode_info /home/user4/work/linkedSV_test/JCX_hg38m.bam.sortbx.bam __STDOUT__ /home/user4/work/linkedSV_test/JCX_hg38m.bam.barcode_statistics | /tools/LinkedSV/scripts/../bin/pigz --fast --processes 1 - > /home/user4/work/linkedSV_test/JCX_hg38m.bam.bcd21.gz
[06/30/2021 22:12:18 (126.693 MB)] extracting low mapq bcd21
[06/30/2021 22:12:30 (126.693 MB)] clustering reads
[06/30/2021 22:12:30 (126.693 MB)] /tools/LinkedSV/scripts/../bin/cluster_reads /home/user4/work/linkedSV_test/JCX_hg38m.bam.bcd21.gz /home/user4/work/linkedSV_test/JCX_hg38m.bam.bcd22 /home/user4/work/linkedSV_test/JCX_hg38m.bam.weird_reads.txt 1 -1 20 1
started round 1 clustering
finished round 1 clustering
time used is 0.02 seconds
mean and sd of inner size: -1.79769e+308, 0
quantiles of inner size:
0.1% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
1% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
5% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
10% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
25% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
50% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
75% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
90% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
95% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
99% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
99.9% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000

quantiles of gap distance:
0.1% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
1% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
5% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
10% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
25% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
50% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
75% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
90% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
95% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
99% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000
99.9% => -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.0000

inner size cut-off = -2147483648
gap distance cut-off = -2147483648
started round 2 clustering
finished round 2 clustering
time used is 0.01 seconds
total number of reads is: 0
total number of weird reads is: 0
[06/30/2021 22:12:35 (126.845 MB)] searching for extremely high coverage region
[06/30/2021 22:12:42 (126.845 MB)] calculating distribution parameters
[06/30/2021 22:12:42 (126.845 MB)] total number of reads in the genome is: -927534
[06/30/2021 22:12:42 (126.845 MB)] calculating fragment parameters from file: /home/user4/work/linkedSV_test/JCX_hg38m.bam.bcd22
[06/30/2021 22:12:42 (126.845 MB)] N95_fragment_length is: -1
Traceback (most recent call last):
  File "/tools/LinkedSV/linkedsv.py", line 313, in <module>
    main()
  File "/tools/LinkedSV/linkedsv.py", line 47, in main
    detect_increased_fragment_ends(args, dbo_args, endpoint_args)
  File "/tools/LinkedSV/linkedsv.py", line 208, in detect_increased_fragment_ends
    global_distribution.estimate_global_distribution(args, dbo_args, endpoint_args, endpoint_args.bcd22_file)
  File "/tools/LinkedSV/scripts/global_distribution.py", line 133, in estimate_global_distribution
    get_fragment_parameters(args, dbo_args, endpoint_args, global_dist_fp, target_bcd22_file, is_fast_mode)
  File "/tools/LinkedSV/scripts/global_distribution.py", line 213, in get_fragment_parameters
    args.fragment_length_lmda = fit_geometric_distribution(frm_length_list, readpair = False)
  File "/tools/LinkedSV/scripts/global_distribution.py", line 171, in fit_geometric_distribution
    k = np.percentile(length_list, cdf2)
  File "/tools/Python-2.7.16/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3707, in percentile
    a, q, axis, out, overwrite_input, interpolation, keepdims)
  File "/tools/Python-2.7.16/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3826, in _quantile_unchecked
    interpolation=interpolation)
  File "/tools/Python-2.7.16/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3405, in _ureduce
    r = func(a, **kwargs)
  File "/tools/Python-2.7.16/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3941, in _quantile_ureduce_func
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "/tools/Python-2.7.16/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 189, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/tools/Python-2.7.16/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.
```

**Comment by fangli80** [comment]
This is strange. Could you please run the following command and see what happens ? You are expected to see a `JCX_hg38m.bam.sortbx.bam` file which should be of similar size to the original bam. 

`/tools/LinkedSV/scripts/../bin/output_bam_coreinfo /home/data/shares/JCX_hg38m.bam | samtools sort -l 1 -m 1G -@ 1 -t BX -o /home/user4/work/linkedSV_test/JCX_hg38m.bam.sortbx.bam -`

And by the way, linkedSV only works with the bam file generated by the 10X Genomics' LongRanger pipeline. The input file is usually named `phased_possorted_bam.bam`. Was your input bam generated from LongRanger ?

**Comment by levinyi** [comment]
“linkedSV only works with the bam file generated by the 10X Genomics' LongRanger pipeline. ”  
oh， that‘s maybe the reason.  my bam file was generated by bwa,  I will run 'LongRanger align' to generate new bam and retry linkedSV.

thanks a lot.
