### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MenggeZhao** [WGLab/LinkedSV#3]
[MM/DD/YYYY HH:MM:SS (XX.XXX MB)] N95_fragment_length is: -1
Traceback (most recent call last):
  File "linkedsv.py", line 278, in <module>
    main()
  File "linkedsv.py", line 43, in main
    detect_increased_fragment_ends(args, dbo_args, endpoint_args)
  File "linkedsv.py", line 178, in detect_increased_fragment_ends
    cluster_reads.cluster_reads(args, dbo_args, endpoint_args)
  File "/LinkedSV/scripts/cluster_reads.py", line 62, in cluster_reads
    global_distribution.estimate_global_distribution (args, dbo_args, endpoint_a                       rgs, endpoint_args.tmpbcd22_file, is_fast_mode = True)
  File "/LinkedSV/scripts/global_distribution.py", line 116, in estimate_global_distribution
    get_fragment_parameters(args, dbo_args, endpoint_args, global_dist_fp, targe                       t_bcd22_file, is_fast_mode)
  File "LinkedSV/scripts/global_distribution.py", line 196, in get_fragment_parameters
    args.fragment_length_lmda = fit_geometric_distribution(frm_length_list, read                       pair = False)
  File "LinkedSV/scripts/global_distribution.py", line 154, in fit_geometric_distribution
    k = np.percentile(length_list, cdf2)
  File "bin/anaconda/envs/py2/lib/python2.7/site-pac                       kages/numpy/lib/function_base.py", line 3707, in percentile
    a, q, axis, out, overwrite_input, interpolation, keepdims)
  File "anaconda/envs/py2/lib/python2.7/site-pac                       kages/numpy/lib/function_base.py", line 3826, in _quantile_unchecked
    interpolation=interpolation)
  File "anaconda/envs/py2/lib/python2.7/site-pac                       kages/numpy/lib/function_base.py", line 3405, in _ureduce
    r = func(a, **kwargs)
  File "anaconda/envs/py2/lib/python2.7/site-pac                       kages/numpy/lib/function_base.py", line 3941, in _quantile_ureduce_func
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "anaconda/envs/py2/lib/python2.7/site-pac                       kages/numpy/core/fromnumeric.py", line 189, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "anaconda/envs/py2/lib/python2.7/site-pac                       kages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.

**Comment by fangli80** [comment]
Fixed. Please pull the latest version. 

Thank you.

**Comment by Martaprf** [comment]
Hi,

I am getting the same error and  I don't know why. Can someone help me.
[06/09/2021 16:02:18 (143.557 MB)] N95_fragment_length is: -1
Traceback (most recent call last):
  File "/home/mferreira/programs/LinkedSV/linkedsv.py", line 313, in <module>
    main()
  File "/home/mferreira/programs/LinkedSV/linkedsv.py", line 47, in main
    detect_increased_fragment_ends(args, dbo_args, endpoint_args)
  File "/home/mferreira/programs/LinkedSV/linkedsv.py", line 208, in detect_increased_fragment_ends
    global_distribution.estimate_global_distribution(args, dbo_args, endpoint_args, endpoint_args.bcd22_file)
  File "/home/mferreira/programs/LinkedSV/scripts/global_distribution.py", line 133, in estimate_global_distribution
    get_fragment_parameters(args, dbo_args, endpoint_args, global_dist_fp, target_bcd22_file, is_fast_mode)
  File "/home/mferreira/programs/LinkedSV/scripts/global_distribution.py", line 213, in get_fragment_parameters
    args.fragment_length_lmda = fit_geometric_distribution(frm_length_list, readpair = False)
  File "/home/mferreira/programs/LinkedSV/scripts/global_distribution.py", line 171, in fit_geometric_distribution
    k = np.percentile(length_list, cdf2)
  File "<__array_function__ internals>", line 6, in percentile
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py", line 3706, in percentile
    a, q, axis, out, overwrite_input, interpolation, keepdims)
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py", line 3826, in _quantile_unchecked
    interpolation=interpolation)
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py", line 3403, in _ureduce
    r = func(a, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py", line 3941, in _quantile_ureduce_func
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "<__array_function__ internals>", line 6, in take
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 194, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.

Thanks

**Comment by fangli80** [comment]
Hi, is your data whole-genome sequencing or targeted sequencing?

**Comment by Martaprf** [comment]
It is whole exome sequencing
