### ISSUE TITLE
IndexError: index -1 is out of bounds for axis 0 with size 0 / Can I use reference genomes from other species (e.g. wildlife)？

### ISSUE THREAD

**Issue by kuangzhuoran** [WGLab/LinkedSV#34]
Can I use reference genomes from other species (e.g. wildlife)
My command is : "pythonlinkedsv.py -i Klg2.chr11.bam -d Klg2 -r chr11.fa -t 4 --somatic_mode"
I didn't set the -v parameter

Here are my logs:
[09/11/2024 19:08:05 (146.670 MB)] searching for extremely high coverage region
[09/11/2024 19:08:09 (145.699 MB)] calculating distribution parameters
[09/11/2024 19:08:09 (145.699 MB)] total number of reads in the genome is: 1948265
[09/11/2024 19:08:09 (145.699 MB)] calculating fragment parameters from file: /beegfs/home/kuangzhuoran/workspace/Migration/08.Inversion/02.link.read/04.LinkedSV/Klg9/Klg9.chr11.bam.bcd22
[09/11/2024 19:08:09 (145.699 MB)] N95_fragment_length is: -1
Traceback (most recent call last):
  File "/beegfs/home/kuangzhuoran/software/LinkedSV/linkedsv.py", line 313, in <module>
    main()
  File "/beegfs/home/kuangzhuoran/software/LinkedSV/linkedsv.py", line 47, in main
    detect_increased_fragment_ends(args, dbo_args, endpoint_args)
  File "/beegfs/home/kuangzhuoran/software/LinkedSV/linkedsv.py", line 208, in detect_increased_fragment_ends
    global_distribution.estimate_global_distribution(args, dbo_args, endpoint_args, endpoint_args.bcd22_file)
  File "/beegfs/home/kuangzhuoran/software/LinkedSV/scripts/global_distribution.py", line 133, in estimate_global_distribution
    get_fragment_parameters(args, dbo_args, endpoint_args, global_dist_fp, target_bcd22_file, is_fast_mode)
  File "/beegfs/home/kuangzhuoran/software/LinkedSV/scripts/global_distribution.py", line 213, in get_fragment_parameters
    args.fragment_length_lmda = fit_geometric_distribution(frm_length_list, readpair = False) 
  File "/beegfs/home/kuangzhuoran/software/LinkedSV/scripts/global_distribution.py", line 171, in fit_geometric_distribution
    k = np.percentile(length_list, cdf2)
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/zhuoran/lib/python3.10/site-packages/numpy/lib/function_base.py", line 4283, in percentile
    return _quantile_unchecked(
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/zhuoran/lib/python3.10/site-packages/numpy/lib/function_base.py", line 4555, in _quantile_unchecked
    return _ureduce(a,
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/zhuoran/lib/python3.10/site-packages/numpy/lib/function_base.py", line 3823, in _ureduce
    r = func(a, **kwargs)
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/zhuoran/lib/python3.10/site-packages/numpy/lib/function_base.py", line 4722, in _quantile_ureduce_func
    result = _quantile(arr,
  File "/beegfs/home/kuangzhuoran/miniconda3/envs/zhuoran/lib/python3.10/site-packages/numpy/lib/function_base.py", line 4831, in _quantile
    slices_having_nans = np.isnan(arr[-1, ...])
IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by kuangzhuoran** [comment]
Sorry, Maybe I do not provide “black_region_bed” and "gap_region_bed".
I am rerunning the program

**Comment by kuangzhuoran** [comment]
Well, Providing “black_region_bed” and "gap_region_bed"    did not make sense

**Comment by kuangzhuoran** [comment]
The paths for pigz and unpigz are incorrect. Creating symbolic links should resolve the issue.

Like:
ln -s ~/software/LinkedSV/pigz/unpigz ~/software/LinkedSV/bin
ln -s ~/software/LinkedSV/pigz/pigz ~/software/LinkedSV/bin
