### ISSUE TITLE
ValueError: data must be 2 dimensions

### ISSUE THREAD

**Issue by jianbiaoli** [WGLab/LinkedSV#9]
Hi,

I keep getting the following error messages:
[11/20/2019 07:05:16 (5.721 GB)] cat  /hwfssz5/20191104linkedsv/somatic/assembly_raw_variants.0.txt  /hwfssz5/20191104linkedsv/somatic/assembly_raw_variants.1.txt  /hwfssz5/20191104linkedsv/somatic/assembly_raw_variants.2.txt  /hwfssz5/20191104linkedsv/somatic/assembly_raw_variants.3.txt  /hwfssz5/20191104linkedsv/somatic/assembly_raw_variants.4.txt  /hwfssz5/20191104linkedsv/somatic/assembly_raw_variants.5.txt  /hwfssz5/20191104linkedsv/somatic/assembly_raw_variants.6.txt  /hwfssz5/20191104linkedsv/somatic/assembly_raw_variants.7.txt  /hwfssz5/20191104linkedsv/somatic/assembly_raw_variants.8.txt  /hwfssz5/20191104linkedsv/somatic/assembly_raw_variants.9.txt  /hwfssz5/20191104linkedsv/somatic/assembly_raw_variants.10.txt  /hwfssz5/20191104linkedsv/somatic/assembly_raw_variants.11.txt  /hwfssz5/20191104linkedsv/somatic/assembly_raw_variants.12.txt  /hwfssz5/20191104linkedsv/somatic/assembly_raw_variants.13.txt  /hwfssz5/20191104linkedsv/somatic/assembly_raw_variants.14.txt  /hwfssz5/20191104linkedsv/somatic/assembly_raw_variants.15.txt  > /hwfssz5/20191104linkedsv/somatic/local_assembly_raw_variants.txt
Traceback (most recent call last):
  File "/hwfssz5/LinkedSV/linkedsv.py", line 313, in <module>
    main()
  File "/hwfssz5/LinkedSV/linkedsv.py", line 63, in main
    detect_sv_from_short_reads.detect_sv_from_short_reads(args, dbo_args, endpoint_args)
  File "/hwfssz5/LinkedSV/scripts/detect_sv_from_short_reads.py", line 84, in detect_sv_from_short_reads
    merge_sv_calls(local_assembly_out_file, short_reads_del_call_file, out_short_read_sv_file, args.tid2chrname, args.chrname2tid)
  File "/hwfssz5/LinkedSV/scripts/detect_sv_from_short_reads.py", line 96, in merge_sv_calls
    local_assembly_del_call_list = svtk.remove_redundantsv(local_assembly_del_call_list)
  File "/hwfssz5/LinkedSV/scripts/svtk.py", line 135, in remove_redundantsv
    tree = cKDTree(coord_list, leafsize = 10000)
  File "ckdtree.pyx", line 525, in scipy.spatial.ckdtree.cKDTree.__init__
ValueError: data must be 2 dimensions

Could you help me with that?

Thank you!

Jianbiao Li

**Comment by fangli80** [comment]
The error happens because the coord_list is empty. I fixed this bug. Please clone the latest version. 
If there are still issues, feel free to let me know. 

Best, 
Li

**Comment by jianbiaoli** [comment]
Thank you very much for your help. I have finished my first run in somatic mode and am now looking at the results. I am wondering how could I know whether a SV is somatic or not?

All the best
Jianbiao Li

**Comment by fangli80** [comment]
Hi Jianbiao, 

Currently, the somatic mode means that LinkedSV can detect SVs with low allele frequencies. If you want to know which SVs are somatic SVs, you will need to run a paired germline sample and remove SV calls in the germline sample. 

Best, 
Li

**Comment by jianbiaoli** [comment]
Hi Li,

I am very sorry for the misunderstanding because of my catachresis. My question is how could I know whether a SV is mosaic(SVs with low variant allele frequencies) or not? As there are no infomation of variant allele frequency in the outputted SV call files. 

All the best
Jianbiao Li

**Comment by fangli80** [comment]
Hi Jianbiao, 

The calculation of allele frequencies has not been implemented yet. For a temporary solution, you can do a rough estimation. Somatic SVs are only detected by the barcode-based methods so please look at the `prefix.filtered_large_svcalls.bedpe` file. For a typical WGS data set, the barcode depth is about 150 and if the number of barcodes (fragments) supporting the SV is < 50 you may consider it as a mosaic SV.

I will implement this later. 
Thanks! 
Li

**Comment by jianbiaoli** [comment]
Thank you very much for your help. Good luck!
